repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest release of pre-commit-hooks
    hooks:
      - id: trailing-whitespace
        additional_dependencies: [flake8-django]