# Generated by Django 4.2.7 on 2023-12-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_link_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.CharField(default='webdevlab/yxogymfppkjpdzuy8gpe', max_length=255),
            preserve_default=False,
        ),
    ]
