# Generated by Django 3.2.8 on 2021-10-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('video_url', models.CharField(max_length=150)),
            ],
        ),
    ]
