# Generated by Django 3.2.8 on 2021-10-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='series',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorialseries'),
        ),
    ]
