# Generated by Django 3.2.8 on 2021-10-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_tutorial_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='series',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorialseries'),
        ),
    ]
