# Generated by Django 3.2.8 on 2021-10-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_remove_tutorial_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='individual',
            field=models.BooleanField(default=True),
        ),
    ]
